parameters:
    personalized_search_index_prefix: 'personalized_search_'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Pimcore\Bundle\PersonalizedSearchBundle\Adapter\SegmentAdapter: ~
    Pimcore\Bundle\PersonalizedSearchBundle\Adapter\PurchaseHistoryAdapter: ~
    Pimcore\Bundle\PersonalizedSearchBundle\Adapter\RelevantProductsAdapter: ~

    Pimcore\Bundle\PersonalizedSearchBundle\IndexAccessProvider\OrderIndexAccessProvider:
        arguments:
            - ['%es_client%']
            - '%personalized_search_index_prefix%'
    Pimcore\Bundle\PersonalizedSearchBundle\IndexAccessProvider\IndexAccessProviderInterface: '@Pimcore\Bundle\PersonalizedSearchBundle\IndexAccessProvider\OrderIndexAccessProvider'

    Pimcore\Bundle\PersonalizedSearchBundle\IndexAccessProvider\CustomerGroupIndexAccessProvider:
        arguments:
            - ['%es_client%']
            - '%personalized_search_index_prefix%'
    Pimcore\Bundle\PersonalizedSearchBundle\IndexAccessProvider\CustomerGroupIndexAccessProviderInterface: '@Pimcore\Bundle\PersonalizedSearchBundle\IndexAccessProvider\CustomerGroupIndexAccessProvider'

    Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\PurchaseHistoryProvider: ~
    Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\PurchaseHistoryInterface: '@Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\PurchaseHistoryProvider'

    Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\CustomerGroupProvider: ~
    Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\CustomerGroupInterface: '@Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\CustomerGroupProvider'

    Pimcore\Bundle\PersonalizedSearchBundle\Customer\PersonalizationAdapterCustomerIdProvider:
        class: Pimcore\Bundle\PersonalizedSearchBundle\Customer\DefaultCustomerIdProvider

    Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\SegmentExtractor\ProductSegmentExtractorInterface:
        class: Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\SegmentExtractor\DummySegmentExtractor

    Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\PersonalizationOrderManagerProvider:
        class: Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\DefaultOrderManagerProvider


    # ---------------------------------------------------------
    # Register all commands of AppBundle as commands
    # ---------------------------------------------------------
    Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\Command\:
        resource: '../../ExtractTransformLoad/Command'
        tags: ['console.command']
