services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Pimcore\Bundle\PersonalizedSearchBundle\Adapter\SegmentAdapter: ~
    Pimcore\Bundle\PersonalizedSearchBundle\Adapter\AccessoryAdapter: ~
    Pimcore\Bundle\PersonalizedSearchBundle\Adapter\PurchaseHistoryAdapter: ~
    Pimcore\Bundle\PersonalizedSearchBundle\Adapter\RelevantProductAdapter: ~

    Pimcore\Bundle\PersonalizedSearchBundle\IndexAccessProvider\OrderIndexAccessProvider: ~
    Pimcore\Bundle\PersonalizedSearchBundle\IndexAccessProvider\RelevantProductIndexAccessProvider: ~
    Pimcore\Bundle\PersonalizedSearchBundle\IndexAccessProvider\IndexAccessProviderInterface: '@Pimcore\Bundle\PersonalizedSearchBundle\IndexAccessProvider\OrderIndexAccessProvider'

    Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\GetterInterface: '@AppBundle\Ecommerce\IndexService\SegmentGetter'
    Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\PurchaseHistoryProvider: ~
    Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\PurchaseHistoryInterface: '@Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\PurchaseHistoryProvider'

    # ---------------------------------------------------------
    # Register all commands of AppBundle as commands
    # ---------------------------------------------------------
    Pimcore\Bundle\PersonalizedSearchBundle\ExtractTransformLoad\Command\:
        resource: '../../ExtractTransformLoad/Command'
        tags: ['console.command']
